//
//  Request.h
//  jianfanjia
//
//  Created by JYZ on 15/8/24.
//  Copyright (c) 2015年 JYZ. All rights reserved.
//

#ifndef jianfanjia_Request_h
#define jianfanjia_Request_h

#import "SendVerifyCode.h"
#import "UserLogin.h"
#import "GetUserRequirement.h"
#import "SendAddRequirement.h"
#import "SendUpdateRequirement.h"
#import "GetOrderableDesigners.h"
#import "OrderDesignder.h"
#import "ReplaceOrderedDesigner.h"
#import "GetOrderedDesignder.h"
#import "ConfirmMeasuringHouse.h"
#import "EvaluateDesigner.h"
#import "GetRequirementPlans.h"
#import "ChoosePlan.h"
#import "LeaveComment.h"
#import "GetComments.h"
#import "StartDecorationProcess.h"
#import "ProcessList.h"
#import "GetProcess.h"
#import "ProductHomePage.h"
#import "DesignerHomePage.h"
#import "QueryProduct.h"
#import "VerifyPhone.h"
#import "UserSignup.h"
#import "UpdatePass.h"
#import "AddFavoriateDesigner.h"
#import "DeleteFavoriteDesigner.h"
#import "ListFavoriteDesigner.h"
#import "UploadImage.h"
#import "UploadImageToProcess.h"
#import "DeleteImageFromProcess.h"
#import "UserGetInfo.h"
#import "UpdateUserInfo.h"
#import "SectionDone.h"
#import "Reschedule.h"
#import "AgreeReschedule.h"
#import "RejectReschedule.h"
#import "Feedback.h"
#import "ListFavoriateProduct.h"
#import "ListFavoriateBeautifulImage.h"
#import "DeleteFavoriateProduct.h"
#import "AddFavoriateProduct.h"
#import "SearchBeautifulImage.h"
#import "SearchDesigner.h"
#import "SearchProduct.h"
#import "GetBeautifulImageHomepage.h"
#import "FavoriteBeautifulImage.h"
#import "UnfavoriteBeautifulImage.h"
#import "WeChatLogin.h"
#import "RefreshSession.h"
#import "BindPhone.h"
#import "BindWechat.h"
#import "GetTopProducts.h"
#import "SearchUserNotification.h"
#import "GetUserNotificationDetail.h"
#import "GetUserUnreadCount.h"
#import "GetDesignerUnreadCount.h"
#import "SearchUserComment.h"
#import "SearchDecLive.h"
#import "AddDiarySet.h"
#import "DeleteDiary.h"
#import "GetDiaryDetail.h"
#import "GetDiarySetDetail.h"
#import "GetDiaryUpdation.h"
#import "SearchDiary.h"
#import "SearchDiarySet.h"
#import "ZanDiary.h"
#import "AddDiary.h"
#import "FavoriteDiarySet.h"
#import "UnfavoriteDiarySet.h"
#import "GetTopDiarySet.h"

#endif
